### ISSUE TITLE
template front and back methods

### ISSUE THREAD

**Issue by JohanMabille** [xtensor-stack/sparrow#33]
The `front` and `back` methods of the buffer class should be template, like the `data` method.

**Comment by jjerphan** [comment]
Should we make sure that the references returned by `front` and `back` are [`std::convertible_to`](https://en.cppreference.com/w/cpp/concepts/convertible_to) the `T` template parameter?

**Comment by JohanMabille** [comment]
Actually this should be hidden in a `buffer_adaptor` class, let's close this issue in favor of #46 .
