### ISSUE TITLE
Implement fixed_size_binary_layout (aka primitive_layout)

### ISSUE THREAD

**Issue by JohanMabille** [xtensor-stack/sparrow#38]
See #14 for details

**Comment by jjerphan** [comment]
Mainly addressed by https://github.com/xtensor-stack/sparrow/pull/31.

A few elements remain:
 - remove non-`const`-qualified ranges
 - add tests for all the iterator
 - clarify the relevance of `fixed_sized_layout_value_iterator` w.r.t #46
